spring:
  application:
    name: ExamBackend
  datasource:
    url: jdbc:postgresql://localhost:5432/examdb
    username: examadmin
    password: examadmin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #Apparently it helps with debugging.

server:
  port: 8080

app:
  jwt:
    secret: "v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYq"
    expiration: 86400000
  security:
    default-candidate-password: "test"